# Generated by Django 4.1.7 on 2023-03-07 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("experience", models.CharField(blank=True, max_length=50)),
                ("audience", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("is_mentor", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "activation_code",
                    models.CharField(default="e5KVb1djZf", max_length=10),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competence", models.CharField(blank=True, max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Russian"),
                            ("kg", "Kyrgyz"),
                        ],
                        default="ru",
                        max_length=2,
                    ),
                ),
                ("site", models.URLField(blank=True, max_length=255)),
                ("twitter", models.URLField(blank=True, max_length=255)),
                ("facebook", models.URLField(blank=True, max_length=255)),
                ("linkedin", models.URLField(blank=True, max_length=255)),
                ("youtube", models.URLField(blank=True, max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="media/")),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_hidden_courses", models.BooleanField(default=False)),
                ("promotions", models.BooleanField(default=False)),
                ("mentor_ads", models.BooleanField(default=False)),
                ("email_ads", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
