# Generated by Django 4.1.7 on 2023-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_managers_alter_user_activation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_code",
            field=models.CharField(default="zJPSAypgX2", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="audience",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="experience",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
