# Generated by Django 4.1.7 on 2023-03-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_user_activation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_code",
            field=models.CharField(default="kErVC14jBp", max_length=10),
        ),
    ]
